const activeInterfaces = {
  "ai21": import('../interfaces/ai21'),
  "ailayer": import('../interfaces/ailayer'),
  "aimlapi": import('../interfaces/aimlapi'),
  "anthropic": import('../interfaces/anthropic'),
  "anyscale": import('../interfaces/anyscale'),
  "azureai": import('../interfaces/azureai'),
  "baseInterface": import('../interfaces/baseInterface'),
  "cloudflareai": import('../interfaces/cloudflareai'),
  "cohere": import('../interfaces/cohere'),
  "corcel": import('../interfaces/corcel'),
  "deepinfra": import('../interfaces/deepinfra'),
  "deepseek": import('../interfaces/deepseek'),
  "fireworksai": import('../interfaces/fireworksai'),
  "forefront": import('../interfaces/forefront'),
  "friendliai": import('../interfaces/friendliai'),
  "gemini": import('../interfaces/gemini'),
  "gooseai": import('../interfaces/gooseai'),
  "groq": import('../interfaces/groq'),
  "huggingface": import('../interfaces/huggingface'),
  "hyperbeeai": import('../interfaces/hyperbeeai'),
  "lamini": import('../interfaces/lamini'),
  "llamacpp": import('../interfaces/llamacpp'),
  "mistralai": import('../interfaces/mistralai'),
  "monsterapi": import('../interfaces/monsterapi'),
  "neetsai": import('../interfaces/neetsai'),
  "novitaai": import('../interfaces/novitaai'),
  "nvidia": import('../interfaces/nvidia'),
  "octoai": import('../interfaces/octoai'),
  "ollama": import('../interfaces/ollama'),
  "openai": import('../interfaces/openai'),
  "perplexity": import('../interfaces/perplexity'),
  "rekaai": import('../interfaces/rekaai'),
  "replicate": import('../interfaces/replicate'),
  "shuttleai": import('../interfaces/shuttleai'),
  "siliconflow": import('../interfaces/siliconflow'),
  "thebai": import('../interfaces/thebai'),
  "togetherai": import('../interfaces/togetherai'),
  "voyage": import('../interfaces/voyage'),
  "watsonxai": import('../interfaces/watsonxai'),
  "writer": import('../interfaces/writer'),
  "zhipuai": import('../interfaces/zhipuai')
};

module.exports = { activeInterfaces };
