const activeInterfaces = {
  "ai21": require('../interfaces/ai21'),
  "ailayer": require('../interfaces/ailayer'),
  "aimlapi": require('../interfaces/aimlapi'),
  "anthropic": require('../interfaces/anthropic'),
  "anyscale": require('../interfaces/anyscale'),
  "azureai": require('../interfaces/azureai'),
  "baseInterface": require('../interfaces/baseInterface'),
  "cloudflareai": require('../interfaces/cloudflareai'),
  "cohere": require('../interfaces/cohere'),
  "corcel": require('../interfaces/corcel'),
  "deepinfra": require('../interfaces/deepinfra'),
  "deepseek": require('../interfaces/deepseek'),
  "fireworksai": require('../interfaces/fireworksai'),
  "forefront": require('../interfaces/forefront'),
  "friendliai": require('../interfaces/friendliai'),
  "gemini": require('../interfaces/gemini'),
  "gooseai": require('../interfaces/gooseai'),
  "groq": require('../interfaces/groq'),
  "huggingface": require('../interfaces/huggingface'),
  "hyperbeeai": require('../interfaces/hyperbeeai'),
  "lamini": require('../interfaces/lamini'),
  "llamacpp": require('../interfaces/llamacpp'),
  "mistralai": require('../interfaces/mistralai'),
  "monsterapi": require('../interfaces/monsterapi'),
  "neetsai": require('../interfaces/neetsai'),
  "novitaai": require('../interfaces/novitaai'),
  "nvidia": require('../interfaces/nvidia'),
  "octoai": require('../interfaces/octoai'),
  "ollama": require('../interfaces/ollama'),
  "openai": require('../interfaces/openai'),
  "perplexity": require('../interfaces/perplexity'),
  "rekaai": require('../interfaces/rekaai'),
  "replicate": require('../interfaces/replicate'),
  "shuttleai": require('../interfaces/shuttleai'),
  "siliconflow": require('../interfaces/siliconflow'),
  "thebai": require('../interfaces/thebai'),
  "togetherai": require('../interfaces/togetherai'),
  "voyage": require('../interfaces/voyage'),
  "watsonxai": require('../interfaces/watsonxai'),
  "writer": require('../interfaces/writer'),
  "zhipuai": require('../interfaces/zhipuai')
};

module.exports = { activeInterfaces };
