const activeProviders = {
  "ai21": require('./providers/ai21'),
  "ailayer": require('./providers/ailayer'),
  "aimlapi": require('./providers/aimlapi'),
  "anyscale": require('./providers/anyscale'),
  "anthropic": require('./providers/anthropic'),
  "cloudflareai": require('./providers/cloudflareai'),
  "cohere": require('./providers/cohere'),
  "corcel": require('./providers/corcel'),
  "deepinfra": require('./providers/deepinfra'),
  "deepseek": require('./providers/deepseek'),
  "fireworksai": require('./providers/fireworksai'),
  "forefront": require('./providers/forefront'),
  "friendliai": require('./providers/friendliai'),
  "gemini": require('./providers/gemini'),
  "gooseai": require('./providers/gooseai'),
  "groq": require('./providers/groq'),
  "huggingface": require('./providers/huggingface'),
  "hyperbeeai": require('./providers/hyperbeeai'),
  "lamini": require('./providers/lamini'),
  "llamacpp": require('./providers/llamacpp'),
  "mistralai": require('./providers/mistralai'),
  "monsterapi": require('./providers/monsterapi'),
  "neetsai": require('./providers/neetsai'),
  "novitaai": require('./providers/novitaai'),
  "nvidia": require('./providers/nvidia'),
  "octoai": require('./providers/octoai'),
  "ollama": require('./providers/ollama'),
  "openai": require('./providers/openai'),
  "perplexity": require('./providers/perplexity'),
  "rekaai": require('./providers/rekaai'),
  "replicate": require('./providers/replicate'),
  "shuttleai": require('./providers/shuttleai'),
  "thebai": require('./providers/thebai'),
  "togetherai": require('./providers/togetherai'),
  "voyage": require('./providers/voyage'),
  "watsonxai": require('./providers/watsonxai'),
  "writer": require('./providers/writer'),
  "zhipuai": require('./providers/zhipuai'),
}

module.exports = { activeProviders };