const activeProviders = {
  "ai21": import('./providers/ai21'),
  "ailayer": import('./providers/ailayer'),
  "aimlapi": import('./providers/aimlapi'),
  "anyscale": import('./providers/anyscale'),
  "anthropic": import('./providers/anthropic'),
  "cloudflareai": import('./providers/cloudflareai'),
  "cohere": import('./providers/cohere'),
  "corcel": import('./providers/corcel'),
  "deepinfra": import('./providers/deepinfra'),
  "deepseek": import('./providers/deepseek'),
  "fireworksai": import('./providers/fireworksai'),
  "forefront": import('./providers/forefront'),
  "friendliai": import('./providers/friendliai'),
  "gemini": import('./providers/gemini'),
  "gooseai": import('./providers/gooseai'),
  "groq": import('./providers/groq'),
  "huggingface": import('./providers/huggingface'),
  "hyperbeeai": import('./providers/hyperbeeai'),
  "lamini": import('./providers/lamini'),
  "llamacpp": import('./providers/llamacpp'),
  "mistralai": import('./providers/mistralai'),
  "monsterapi": import('./providers/monsterapi'),
  "neetsai": import('./providers/neetsai'),
  "novitaai": import('./providers/novitaai'),
  "nvidia": import('./providers/nvidia'),
  "octoai": import('./providers/octoai'),
  "ollama": import('./providers/ollama'),
  "openai": import('./providers/openai'),
  "perplexity": import('./providers/perplexity'),
  "rekaai": import('./providers/rekaai'),
  "replicate": import('./providers/replicate'),
  "shuttleai": import('./providers/shuttleai'),
  "thebai": import('./providers/thebai'),
  "togetherai": import('./providers/togetherai'),
  "voyage": import('./providers/voyage'),
  "watsonxai": import('./providers/watsonxai'),
  "writer": import('./providers/writer'),
  "zhipuai": import('./providers/zhipuai'),
}

module.exports = { activeProviders };